services:
  - type: web
    name: quizroom-hub-backend
    runtime: python
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn quiz_room_hub.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,aykrimino.github.io"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://aykrimino.github.io,http://localhost:3000"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: DEVELOPMENT
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: quizroom-hub-db
          property: connectionString

databases:
  - name: quizroom-hub-db
    databaseName: quizroom_hub
    user: quizroom_hub_user
    plan: free
